# Generated by Django 3.0.8 on 2023-01-08 16:00

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_apellidos', models.CharField(max_length=70)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='Perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuario', models.CharField(max_length=20, unique=True)),
                ('clave', fernet_fields.fields.EncryptedTextField()),
                ('entrenamiento_facial', models.BooleanField(default=False)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Persona.Personas')),
            ],
        ),
    ]
